apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveaaz-frontend
  namespace: liveaaz-frontend
  labels:
    name: liveaaz-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: liveaaz-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: liveaaz-frontend
    spec:
      containers:
      - image: nagarjunns/liveaaz-frontend:1.4
        name: liveaaz-frontend
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: frontend-configmap